import type { AuditEvent, Incident, ServiceHealth, TimelineEntry } from "../../shared/types.js";

export const DEMO_RESET_AT = "2026-09-24T12:00:00.000Z";

export const seedIncidents: Incident[] = [
  {
    id: "INC-1042",
    title: "Checkout failures after payment-service rollout",
    summary:
      "Customers are receiving payment authorization errors during checkout after the latest payment-service deployment.",
    severity: "P1",
    status: "Triggered",
    service: "Checkout API",
    regions: ["us-east-1", "eu-west-1"],
    customerImpact: "37% of checkout attempts are failing before order confirmation.",
    affectedCustomers: 18420,
    assignee: null,
    startedAt: "2026-09-24T11:42:00.000Z",
    updatedAt: "2026-09-24T11:58:00.000Z",
  },
  {
    id: "INC-1041",
    title: "Elevated product search latency",
    summary: "Search p95 latency is above the customer-facing SLO in North America.",
    severity: "P2",
    status: "Monitoring",
    service: "Product Search",
    regions: ["us-east-1"],
    customerImpact: "Search results are loading slowly for approximately 8% of sessions.",
    affectedCustomers: 3910,
    assignee: "Avery Chen",
    startedAt: "2026-09-24T09:17:00.000Z",
    updatedAt: "2026-09-24T11:31:00.000Z",
  },
  {
    id: "INC-1040",
    title: "Transactional email delivery delay",
    summary: "Order confirmation emails are delayed while the provider queue drains.",
    severity: "P3",
    status: "Investigating",
    service: "Notifications",
    regions: ["global"],
    customerImpact: "Confirmation messages are delayed by 8–14 minutes; orders are unaffected.",
    affectedCustomers: 1260,
    assignee: "Jordan Bell",
    startedAt: "2026-09-24T08:26:00.000Z",
    updatedAt: "2026-09-24T10:48:00.000Z",
  },
  {
    id: "INC-1039",
    title: "Analytics ingestion backlog",
    summary: "A transient warehouse connection issue delayed internal reporting events.",
    severity: "P4",
    status: "Resolved",
    service: "Analytics Pipeline",
    regions: ["us-west-2"],
    customerImpact: "No direct customer impact; internal dashboards were 22 minutes behind.",
    affectedCustomers: 0,
    assignee: "Sam Rivera",
    startedAt: "2026-09-24T05:04:00.000Z",
    updatedAt: "2026-09-24T07:12:00.000Z",
  },
];

export const seedTimeline: Omit<TimelineEntry, "id">[] = [
  {
    incidentId: "INC-1042",
    occurredAt: "2026-09-24T11:42:00.000Z",
    kind: "signal",
    title: "Checkout error-rate alert fired",
    detail: "Payment authorization failures crossed the 10% P1 threshold in us-east-1.",
    author: "Datadog demo adapter",
  },
  {
    incidentId: "INC-1042",
    occurredAt: "2026-09-24T11:44:00.000Z",
    kind: "signal",
    title: "Impact confirmed in a second region",
    detail: "The same failure signature appeared in eu-west-1; database health remained normal.",
    author: "Service health monitor",
  },
  {
    incidentId: "INC-1042",
    occurredAt: "2026-09-24T11:47:00.000Z",
    kind: "deployment",
    title: "Recent deployment correlated",
    detail:
      "payment-service v4.18.0 completed 6 minutes before the alert. The release changed merchant token cache keys.",
    author: "Deployment demo adapter",
  },
  {
    incidentId: "INC-1042",
    occurredAt: "2026-09-24T11:51:00.000Z",
    kind: "signal",
    title: "Token-cache hit rate collapsed",
    detail:
      "Merchant token cache hit rate fell from 96% to 18%; authorization dependency latency increased 4.7x.",
    author: "Datadog demo adapter",
  },
  {
    incidentId: "INC-1042",
    occurredAt: "2026-09-24T11:58:00.000Z",
    kind: "note",
    title: "Rollback candidate identified",
    detail:
      "v4.17.3 is the last known-good payment-service build. No database saturation or network loss is present.",
    author: "Release engineering",
  },
  {
    incidentId: "INC-1041",
    occurredAt: "2026-09-24T09:17:00.000Z",
    kind: "signal",
    title: "Search latency SLO breached",
    detail: "p95 latency rose to 1.8 seconds following a traffic spike.",
    author: "Service health monitor",
  },
  {
    incidentId: "INC-1041",
    occurredAt: "2026-09-24T11:31:00.000Z",
    kind: "note",
    title: "Capacity adjustment stable",
    detail: "Additional replicas reduced p95 latency to 710 ms. Team is monitoring.",
    author: "Avery Chen",
  },
  {
    incidentId: "INC-1040",
    occurredAt: "2026-09-24T08:26:00.000Z",
    kind: "signal",
    title: "Provider queue delay detected",
    detail: "Transactional email provider reported elevated queue depth.",
    author: "PagerDuty demo adapter",
  },
  {
    incidentId: "INC-1039",
    occurredAt: "2026-09-24T07:12:00.000Z",
    kind: "status",
    title: "Incident resolved",
    detail: "Warehouse connectivity recovered and the ingestion backlog drained.",
    author: "Sam Rivera",
  },
];

export const seedServiceHealth: ServiceHealth[] = [
  {
    service: "Checkout API",
    status: "outage",
    latencyMs: 1320,
    errorRate: 37.2,
    lastCheckedAt: "2026-09-24T11:59:30.000Z",
    detail: "Payment authorization errors are blocking checkout completion.",
  },
  {
    service: "Payment Service",
    status: "outage",
    latencyMs: 2480,
    errorRate: 41.8,
    lastCheckedAt: "2026-09-24T11:59:26.000Z",
    detail: "Merchant token cache misses are overloading the authorization dependency.",
  },
  {
    service: "Orders Database",
    status: "healthy",
    latencyMs: 24,
    errorRate: 0.02,
    lastCheckedAt: "2026-09-24T11:59:28.000Z",
    detail: "Connection pool, write latency, and replication are normal.",
  },
  {
    service: "Product Search",
    status: "degraded",
    latencyMs: 710,
    errorRate: 0.8,
    lastCheckedAt: "2026-09-24T11:59:22.000Z",
    detail: "Latency is recovering after a capacity adjustment.",
  },
  {
    service: "Notifications",
    status: "degraded",
    latencyMs: 840000,
    errorRate: 0.1,
    lastCheckedAt: "2026-09-24T11:59:18.000Z",
    detail: "Email provider queue is draining; sends are delayed.",
  },
  {
    service: "Analytics Pipeline",
    status: "healthy",
    latencyMs: 180,
    errorRate: 0,
    lastCheckedAt: "2026-09-24T11:59:12.000Z",
    detail: "Ingestion and warehouse connectivity are normal.",
  },
];

export const seedAuditEvents: Omit<AuditEvent, "id">[] = [
  {
    incidentId: null,
    sessionId: null,
    occurredAt: DEMO_RESET_AT,
    actor: "demo-system",
    action: "demo_data_reset",
    arguments: { dataset: "canonical-v1" },
    outcome: "success",
    detail: "Canonical incident demo data restored.",
  },
];
